media:
  input: src/img
  output: /src/img
content:
  - name: biztech_manual
    label: "BizTech 原創文章"
    type: collection
    path: "data/manual_articles"
    filename: "{slug}.json"
    format: json
    fields:
      - name: title
        label: "文章標題"
        type: string
        required: true
      - name: author
        label: "作者"
        type: string
        default: "Patrick Cheung"
      - name: date
        label: "發布日期"
        type: date
      - name: image
        label: 封面圖片
        widget: image # 或者 file，視 PagesCMS 支援的元件而定
        media_folder: src/img # 設定你圖片上傳後要存放的資料夾
      - name: content
        label: "文章內文"
        type: rich-text
