media:
  input: src/img
  output: src/img
content:
  - name: biztech_manual
    label: "BizTech 原創文章"
    type: collection
    path: "data/manual_articles"
    filename: "{slug}.json"
    format: json
    fields:
      - name: is_pinned
        label: "是否置頂 (欄位卡片置頂)"
        type: boolean
        default: false
      - name: category
        label: "文章分類"
        type: string
        default: "BizTech"
        hidden: true
      - name: title
        label: "文章標題"
        type: string
        required: true
      - name: subtitle
        label: "文章小標題 / 摘要"
        type: string
      - name: author
        label: "作者"
        type: string
        default: "Patrick Cheung"
      - name: date
        label: "發布日期"
        type: date
      - name: image
        label: "封面圖片"
        type: image
      - name: image_caption
        label: "封面圖片註明"
        type: string
      - name: content
        label: "文章內文"
        type: rich-text

  - name: insights_manual
    label: "Insights 原創文章"
    type: collection
    path: "data/insights_manual_articles"
    filename: "{slug}.json"
    format: json
    fields:
      - name: is_pinned
        label: "是否置頂 (欄位卡片置頂)"
        type: boolean
        default: false
      - name: category
        label: "文章分類"
        type: string
        default: "Insights"
        hidden: true
      - name: title
        label: "文章標題"
        type: string
        required: true
      - name: subtitle
        label: "文章小標題 / 摘要"
        type: string
      - name: author
        label: "作者"
        type: string
        default: "Patrick Cheung"
      - name: date
        label: "發布日期"
        type: date
      - name: image
        label: "封面圖片"
        type: image
      - name: image_caption
        label: "封面圖片註明"
        type: string
      - name: content
        label: "文章內文"
        type: rich-text

  - name: spotlight_manual
    label: Spotlight 專題採訪
    type: collection
    path: "data/spotlight_manual_articles"
    format: yaml-frontmatter
    extension: md
    fields:
      - name: is_pinned
        label: "是否置頂 (欄位卡片置頂)"
        type: boolean
        default: false
      - name: category
        label: "文章分類"
        type: string
        default: "Spotlight"
        hidden: true
      - name: title
        label: "文章標題"
        type: string
        required: true
      - name: subtitle
        label: "文章小標題 / 摘要"
        type: string
      - name: author
        label: "作者"
        type: string
        default: "Patrick Cheung"
      - name: date
        label: "發布日期"
        type: date
      - name: image
        label: "封面圖片"
        type: image
      - name: image_caption
        label: "封面圖片註明"
        type: string
      - name: content
        label: "文章內文"
        type: rich-text
